Feature/croquis added stage, design responsive.
bragonya/TicketsWeb pull request #1
Opened 2019-11-27 19:41 UTC by skrillfer

2019-11-27 20:51 UTC, bragonya1992 commented on src/assets/seat-structure.js
> +const main_stage = {
Podrías renombrar esto a: event_seats_structure

2019-11-27 21:00 UTC, bragonya1992 commented on src/assets/seat-structure.js
> +            name:'Sala Lounge',
Si no es mucho el tiempo, ¿podríamos agregar un nuevo campo para manejar el colod de cada sección?

Si lleva mucho tiempo, dejemoslo para después.

2019-11-27 21:04 UTC, bragonya1992 commented on src/components/legend-croquis/legend-croquis.component.jsx
> +            Free
Los nombres de las leyendas van en español, dado que los usuarios van a ver esto directamente en la página.

2019-11-27 21:06 UTC, bragonya1992 commented on src/components/section/section.component.jsx
> +    const sortedSizes = sizes.sort((a,b)=> b-a);
Solo me gustaría entender por qué es necesario este sort.

2019-11-27 21:08 UTC, bragonya1992 requested changes
Dejé algunas sugerencias pequeñas, pero por lo general lo veo bien :)

2019-11-27 21:36 UTC, skrillfer commented on src/components/legend-croquis/legend-croquis.component.jsx
> +            Free
commit 424aaf447064a379bfad7364190f800c7f4f63dd

2019-11-27 21:39 UTC, skrillfer commented on src/components/section/section.component.jsx
> +    const sortedSizes = sizes.sort((a,b)=> b-a);
sortedSizes ordena de forma descendente el numero de columnas de cada fila, para obtener el mayor para pitar el rango en el encabezado.

2019-11-27 21:42 UTC, skrillfer commented on src/assets/seat-structure.js
> +            name:'Sala Lounge',
Lo voy a trabajar en el feature para agregar el asset del escenario.

2019-11-27 21:43 UTC, bragonya1992 commented on src/components/section/section.component.jsx
> +    const sortedSizes = sizes.sort((a,b)=> b-a);
No podrías usar una función como `max`?

2019-11-27 21:44 UTC, bragonya1992 commented on src/assets/seat-structure.js
> +            name:'Sala Lounge',
Ok, listo

2019-11-27 21:49 UTC, bragonya1992 commented on src/components/section/section.component.jsx
> +    const headers = Array.from({length: sortedSizes[0]}, (v, i) => i+1);
Necesitamos algo acá para que no crashee en caso de que `sortedSizes[0]` sea un array vacío. (Creo que `max` solucionaría eso no?)

2019-11-27 21:54 UTC, skrillfer commented on src/components/section/section.component.jsx
> +    const sortedSizes = sizes.sort((a,b)=> b-a);
commit ee23c5c80a1d33ecbcdc2874eae2c8add3417768

2019-11-27 21:58 UTC, bragonya1992 commented on src/components/section/section.component.jsx
> +    const headers = Array.from({length: sortedSizes[0]}, (v, i) => i+1);
Mucho mejor, gracias 👍

2019-11-27 21:58 UTC, bragonya1992 approved these changes

2019-11-28 06:13 UTC, kenny08gt approved these changes

2019-11-28 06:21 UTC, merged

2019-11-28 06:36 UTC, kenny08gt commented on src/components/croquis/croquis.styles.scss
> +}
Agregale un selector mayor que agrupe todo. Ese cambio a la clase container rompe el estilo de la homepage

2019-11-28 06:36 UTC, kenny08gt commented on src/components/legend-croquis/legend-croquis.styles.scss
> +}
Igual aqui, agregale un selector mayor que agrupe todo

2019-11-28 06:36 UTC, kenny08gt commented on src/components/section/section.styles.scss
> +
igual, un selector que agrupe todo